version: '3'

networks:
  shared-networks:
    driver: bridge

services:
  db:
    container_name: sales_db
    networks:
      - shared-networks
    image: postgres:11.1-alpine
    ports:
      - 5432:5432